/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package id.ac.uniska.pbo2.p03;

import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.FlatLightLaf;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/**
 *
 * @author MyBook Hype AMD
 */
public class FormTiketTravel extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormTiketTravel.class.getName());

    /**
     * Creates new form FormTiketTravel
     */
    public FormTiketTravel() {
        initComponents();
        
        // Kode tambahan ditulis setelah initComponents(), di luar blok abu-abu buatan NetBeans
        namaPemesanField.putClientProperty("JTextField.placeholderText", "Nama sesuai KTP");
        nomorHPField.putClientProperty("JTextField.placeholderText", "08xxxxxxxxxx");
        getRootPane().setDefaultButton(pesanButton);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kelasButtonGroup = new javax.swing.ButtonGroup();
        namaPemesanLabel = new javax.swing.JLabel();
        nomorHPLabel = new javax.swing.JLabel();
        kotaTujuanLabel = new javax.swing.JLabel();
        kelasLabel = new javax.swing.JLabel();
        fasilitasTambahanLabel = new javax.swing.JLabel();
        catatanLabel = new javax.swing.JLabel();
        namaPemesanField = new javax.swing.JTextField();
        nomorHPField = new javax.swing.JTextField();
        kotaTujuanComboBox = new javax.swing.JComboBox<>();
        ekonomiRadioButton = new javax.swing.JRadioButton();
        bisnisRadioButton = new javax.swing.JRadioButton();
        eksekutifRadioButton = new javax.swing.JRadioButton();
        bagasiCheckBox = new javax.swing.JCheckBox();
        makanCheckBox = new javax.swing.JCheckBox();
        asuransiCheckBox = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        catatanTextArea = new javax.swing.JTextArea();
        pesanButton = new javax.swing.JButton();
        modeGelapButton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Pemesanan Tiket Travel");

        namaPemesanLabel.setText("Nama Pemesan");

        nomorHPLabel.setText("Nomor HP");

        kotaTujuanLabel.setText("Kota Tujuan");

        kelasLabel.setText("Kelas");

        fasilitasTambahanLabel.setText("Fasilitas Tambahan");

        catatanLabel.setText("Catatan");

        kotaTujuanComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banjarbaru", "Martapura", "Palangka Raya", "Samarinda", "Balikpapan" }));

        kelasButtonGroup.add(ekonomiRadioButton);
        ekonomiRadioButton.setSelected(true);
        ekonomiRadioButton.setText("Ekonomi");

        kelasButtonGroup.add(bisnisRadioButton);
        bisnisRadioButton.setText("Bisnis");

        kelasButtonGroup.add(eksekutifRadioButton);
        eksekutifRadioButton.setText("Eksekutif");

        bagasiCheckBox.setText("Bagasi");

        makanCheckBox.setText("Makan");

        asuransiCheckBox.setText("Asuransi");

        catatanTextArea.setColumns(20);
        catatanTextArea.setRows(3);
        jScrollPane1.setViewportView(catatanTextArea);

        pesanButton.setText("Pesan");
        pesanButton.addActionListener(this::pesanButtonActionPerformed);

        modeGelapButton.setText("Mode Gelap");
        modeGelapButton.addActionListener(this::modeGelapButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(kotaTujuanLabel)
                        .addGap(61, 61, 61)
                        .addComponent(kotaTujuanComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namaPemesanLabel)
                            .addComponent(nomorHPLabel))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomorHPField)
                            .addComponent(namaPemesanField)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(pesanButton)
                            .addGap(18, 18, 18)
                            .addComponent(modeGelapButton))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(kelasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fasilitasTambahanLabel)
                                .addComponent(catatanLabel))
                            .addGap(23, 23, 23)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(bagasiCheckBox)
                                    .addGap(18, 18, 18)
                                    .addComponent(makanCheckBox)
                                    .addGap(18, 18, 18)
                                    .addComponent(asuransiCheckBox))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(ekonomiRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(bisnisRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(eksekutifRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaPemesanLabel)
                    .addComponent(namaPemesanField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomorHPLabel)
                    .addComponent(nomorHPField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kotaTujuanLabel)
                    .addComponent(kotaTujuanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kelasLabel)
                    .addComponent(ekonomiRadioButton)
                    .addComponent(bisnisRadioButton)
                    .addComponent(eksekutifRadioButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fasilitasTambahanLabel)
                    .addComponent(bagasiCheckBox)
                    .addComponent(makanCheckBox)
                    .addComponent(asuransiCheckBox))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(catatanLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modeGelapButton)
                    .addComponent(pesanButton))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modeGelapButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeGelapButtonActionPerformed
        // TODO add your handling code here:
        gantiTema(modeGelapButton.isSelected());
    }//GEN-LAST:event_modeGelapButtonActionPerformed

    private void pesanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesanButtonActionPerformed
        // TODO add your handling code here:
        tampilkanRingkasan();
    }//GEN-LAST:event_pesanButtonActionPerformed

    private void tampilkanRingkasan() {
        String kelas;
        if (ekonomiRadioButton.isSelected()) {
            kelas = "Ekonomi";
        } else if (bisnisRadioButton.isSelected()) {
            kelas = "Bisnis";
        } else {
            kelas = "Eksekutif";
        }

        List<String> fasilitas = new ArrayList<>();
        for (JCheckBox cb : List.of(bagasiCheckBox, makanCheckBox, asuransiCheckBox)) {
            if (cb.isSelected()) {
                fasilitas.add(cb.getText());
            }
        }

        String catatan = catatanTextArea.getText().trim();

        String pesan = "Nama Pemesan: " + namaPemesanField.getText()
                + "\nNomor HP: " + nomorHPField.getText()
                + "\nKota Tujuan: " + kotaTujuanComboBox.getSelectedItem()
                + "\nKelas: " + kelas
                + "\nFasilitas Tambahan: " + (fasilitas.isEmpty() ? "-" : String.join(", ", fasilitas))
                + "\nCatatan: " + (catatan.isEmpty() ? "-" : catatan);

        JOptionPane.showMessageDialog(this, pesan, "Ringkasan Pemesanan Tiket",
                JOptionPane.INFORMATION_MESSAGE);
    }

    private void gantiTema(boolean gelap) {
        if (gelap) {
            FlatDarkLaf.setup();
        } else {
            FlatLightLaf.setup();
        }
        FlatLaf.updateUI(); // terapkan tema baru ke semua jendela yang terbuka
        modeGelapButton.setText(gelap ? "Mode Terang" : "Mode Gelap");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        // Blok Nimbus buatan NetBeans diganti dengan tema FlatLaf
        FlatLightLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormTiketTravel().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox asuransiCheckBox;
    private javax.swing.JCheckBox bagasiCheckBox;
    private javax.swing.JRadioButton bisnisRadioButton;
    private javax.swing.JLabel catatanLabel;
    private javax.swing.JTextArea catatanTextArea;
    private javax.swing.JRadioButton ekonomiRadioButton;
    private javax.swing.JRadioButton eksekutifRadioButton;
    private javax.swing.JLabel fasilitasTambahanLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.ButtonGroup kelasButtonGroup;
    private javax.swing.JLabel kelasLabel;
    private javax.swing.JComboBox<String> kotaTujuanComboBox;
    private javax.swing.JLabel kotaTujuanLabel;
    private javax.swing.JCheckBox makanCheckBox;
    private javax.swing.JToggleButton modeGelapButton;
    private javax.swing.JTextField namaPemesanField;
    private javax.swing.JLabel namaPemesanLabel;
    private javax.swing.JTextField nomorHPField;
    private javax.swing.JLabel nomorHPLabel;
    private javax.swing.JButton pesanButton;
    // End of variables declaration//GEN-END:variables
}
